// Generated by Xata Codegen 0.23.2. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "task",
    columns: [
      { name: "title", type: "string" },
      { name: "description", type: "text" },
      { name: "done", type: "bool" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Task = InferredTypes["task"];
export type TaskRecord = Task & XataRecord;

export type DatabaseSchema = {
  task: TaskRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://alexsoncoelho21-s-workspace-pp71eo.us-east-1.xata.sh/db/dev",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
